name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  he: ^0.0.4
  json_annotation: ^4.9.0
  logger: ^2.5.0
  markdown_widget: ^2.3.2+8
  riverpod: ^2.6.1
  toastification: ^3.0.2

dev_dependencies:
  build_runner: any
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
